### ISSUE TITLE
Caanot find "ValidationGtBlocksSrgb.mat"

### ISSUE THREAD

**Issue by shankerabhigyan** [huanzheng551803/Real_R2R_denoising#5]
var_gt = scio.loadmat(os.path.join(opt.val_path,'ValidationGtBlocksSrgb.mat'))['ValidationGtBlocksSrgb'].astype(np.float32)/255.
line 125 in train_sidd_dncnn.py raises the error "No such file or Directory"
at which step is this file supposed to be generated?

**Comment by huanzheng551803** [comment]
It is the validation dataset and it can be downloaded in Sidd website!
